### ISSUE TITLE
any tip for wired

### ISSUE THREAD

**Issue by pipiscrew** [ctmckenna/paywall-ninja#2]
ex.
> https://www.wired.com/story/lightweight-encryption-internet-of-things/
> https://www.wired.com/story/pfas-chemicals-bloodstream-plant-spy-chips-bloomberg-apple/

disabling the opacity is fine & scrollable, but 'sign in' appears.

![image](https://user-images.githubusercontent.com/3852762/69480057-f1a07a80-0dfb-11ea-9d32-a70839800694.png)

**Comment by ctmckenna** [comment]
Wired should work with latest version now: https://github.com/ctmckenna/paywall-ninja/commit/f8d52f15c1e2272f7363e96b73ce744e29a13caf
