### ISSUE TITLE
bypass youtube advert by simple replacing the domain

### ISSUE THREAD

**Issue by pipiscrew** [ctmckenna/paywall-ninja#3]
hi, 

using the new

https://bit.ly/34mTitM

any #url opened# to a #new tab# and is starting by 

> youtube.com
> or
> youtu.be

to be replaced by invidio!!

**Comment by ctmckenna** [comment]
Good to know! But I'm not going to do anything with that here.  I want this plugin to only handle paywalls as people can get an adblocker to bypass ads
