### ISSUE TITLE
wsj no work

### ISSUE THREAD

**Issue by pipiscrew** [ctmckenna/paywall-ninja#6]
> https://www.wsj.com/articles/huawei-manages-to-make-smartphones-without-american-chips-11575196201

when click the addon icon, the default menu appears

![575](https://user-images.githubusercontent.com/3852762/69983554-e56c9980-152e-11ea-9a9e-8f3692b24a78.png)

**Comment by ctmckenna** [comment]
Should be fixed with this commit: https://github.com/ctmckenna/paywall-ninja/commit/934361527ab4a9eda2ed49027ed4147a7ea1d83d.

But let me know if you see it again
